### ISSUE TITLE
Duplicate argument `argparse.ArgumentError` in 01.cli_demonstration.ipynb

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet-notebooks#11]
* IceNet version: 0.2.6
* Python version: 3.8.18
* Operating System: Windows (WSL2 Ubuntu 22.04.3 LTS)

### Description

Running `icenet_data_era5 --help` in [01.cli_demonstration.ipynb](https://github.com/icenet-ai/icenet-notebooks/blob/main/01.cli_demonstration.ipynb) in cell 3 (and so, equivalently in bash) causes `argparse.ArgumentError` exception.

This has been raised in main icenet module icenet-ai/icenet#185. Caused by duplicate short argument `-p` being defined.

#### Expected outcome

Successfully show help for the executable.

### What I did

```bash
$ icenet_data_era5 --help

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/icenet/bin/icenet_data_era5", line 33, in <module>
    sys.exit(load_entry_point('icenet', 'console_scripts', 'icenet_data_era5')())
  File "/mnt/c/Users/user/git/BAS/icenet/icenet/icenet/data/interfaces/cds.py", line 263, in main
    args = download_args(choices=["cdsapi", "toolbox"],
  File "/mnt/c/Users/user/git/BAS/icenet/icenet/icenet/utils.py", line 83, in wrapper
    parsed_args = func(*args, **kwargs)
  File "/mnt/c/Users/user/git/BAS/icenet/icenet/icenet/data/cli.py", line 144, in download_args
    ap.add_argument(*arg[0], **arg[1])
  File "/home/user/anaconda3/envs/icenet/lib/python3.8/argparse.py", line 1386, in add_argument
    return self._add_action(action)
  File "/home/user/anaconda3/envs/icenet/lib/python3.8/argparse.py", line 1749, in _add_action
    self._optionals._add_action(action)
  File "/home/user/anaconda3/envs/icenet/lib/python3.8/argparse.py", line 1590, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/home/user/anaconda3/envs/icenet/lib/python3.8/argparse.py", line 1400, in _add_action
    self._check_conflict(action)
  File "/home/user/anaconda3/envs/icenet/lib/python3.8/argparse.py", line 1539, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/home/user/anaconda3/envs/icenet/lib/python3.8/argparse.py", line 1548, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -p/--do-not-postprocess: conflicting option string: -p
```

**Comment by bnubald** [comment]
Issue has been fixed in main `icenet` library repo.

https://github.com/icenet-ai/icenet/commit/ecc2ee0d003691008610660471c33cffc5ff1c11

Fixed in v0.2.7_dev version:

https://github.com/icenet-ai/icenet/releases/tag/v0.2.7
